### ISSUE TITLE
How to change transparency in getTransformMatrix？

### ISSUE THREAD

**Issue by disonwei** [TBR-Group-software/transformable_list_view#6]
Matrix4 getTransformMatrix(TransformableListItem item) {
  /// final scale of child when the animation is completed
  const endScaleBound = 0.4;

  /// 0 when animation completed and [scale] == [endScaleBound]
  /// 1 when animation starts and [scale] == 1
  final animationProgress = item.visibleExtent / item.size.height;

  /// result matrix
  final paintTransform = Matrix4.identity();

  /// animate only if item is on edge
  if (item.position != TransformableListItemPosition.middle) {
    final scale = endScaleBound + ((1 - endScaleBound) * animationProgress);
    final opacity =
        (endScaleBound + ((1 - endScaleBound) * animationProgress)) / 2;

    print(scale);
    print(opacity);

    paintTransform
      ..translate(item.size.width / 2)
      ..scale(scale)
      ..translate(-item.size.width / 2);

    // paintTransform.setEntry(3, 3, opacity); // 添加透明度变换
  }

  return paintTransform;
}

How to modify transparency changes synchronously in this code?

**Comment by theSharpestTool** [comment]
Hi @disonwei! Thanks for your issue report. Unfortunately `opacity` is not part of `Matrix4`. Since this package uses only matrix transformations, transparency changes are not currently supported.
