### ISSUE TITLE
TransformableSliverList example, and support for TransformableSliverListView.builder

### ISSUE THREAD

**Issue by alguintu** [TBR-Group-software/transformable_list_view#9]
It would be helpful to get an example of what delegate to use for `TransformableSliverList` as well a `.builder` named constructor to make this package more usable.

**Comment by theSharpestTool** [comment]
Hi @alguintu Thank you for your feedback! I'm going to update the readme with this example and add new `.builder` `.list` and `.separated` constructors on the next release. Currently the use of `TransformableSliverList` is absolutely identical to `SliverList` so you can use all the delegates that work with `SliverList`.
